### ISSUE TITLE
Example App has dates jumbled up

### ISSUE THREAD

**Issue by jennablkwll** [ME-MarvinE/XCalendar#100]
``**Describe the bug**
In trying the Xamarin Forms sample app (click on the specific examples like "Selection example") on my Android, the dates are mixed up on the calendar view.  It seems maybe the weekends are what are mixed up. 

**Expected behavior**
The calendar dates should display in order as expected unless customized to not be.

**Steps to reproduce OR link to code**
Try the sample Xamarin Forms app on Android.  Haven't tried iOS.

**Xamarin Forms or .NET MAUI (If related to UI)**
Xamarin Forms

**Additional context (Optional)**

**Device Info (Optional)**
Device Model: Google pixel 6 pro
Android Version:  Android 13
IOS Version:
Windows Version:

**Comment by jennablkwll** [comment]
![Screenshot_20230119-163207](https://user-images.githubusercontent.com/96692692/213578019-aeb627ea-36a2-4b79-9419-03ad9ff831a6.png)

**Comment by jennablkwll** [comment]
After a little more testing, it seems it happens when the Calendar.StartOfWeek is not set to Monday.  That's why it doesnt happen on Playground view.

**Comment by ME-MarvinE** [comment]
The default value of the `StartOfWeek` property is to use your device's culture's start of the week. I think it's `System.Culture.CurrentCulture.StartOfWeek`. For example for America, the Calendar would start on Sunday by default.

If you want to change the value, just set the `StartOfWeek` property to the `DayOfWeek` you want.

**Comment by jennablkwll** [comment]
Yes - I am in the US so I prefer start of week set to Sunday.  However, as shown in the screenshot, I also would expect the dates to still remain in order.  The date starts with Sunday, 14th, then Monday the 8th.  I would have expected Sunday 15th, Monday 16th, Tuesday 17, and so on.
To get around the issue, I've had to start my day of the week to Monday in order for the dates to still display in order.

**Comment by ME-MarvinE** [comment]
I'm confident I've found the cause of the issue. I'll fix this later today and get a new version out. I'll notify you when this is done.

**Comment by ME-MarvinE** [comment]
@jennablkwll Version 4.3.1 is availabe on nuget and contains the fix.
