### ISSUE TITLE
Invalid dates lost after navigating months

### ISSUE THREAD

**Issue by jennablkwll** [ME-MarvinE/XCalendar#101]
**Describe the bug**
I set invalid dates on page load.  The dates are showing the invalid color as expected.  When I navigate to a different month and return, the invalid color is gone and I can select them.

**Expected behavior**
The invalid property should still be set regardless of navigation

**Steps to reproduce OR link to code**
Set invalid dates.  Then navigate away and come back.  Invalid dates will be gone.

**Xamarin Forms or .NET MAUI (If related to UI)**
Xamarin Forms

**Additional context (Optional)**

**Device Info (Optional)**
Device Model:  Google Pixel Pro 6
Android Version:  13
IOS Version:
Windows Version:

**Comment by ME-MarvinE** [comment]
I would like to reproduce the issue. How would I "set invalid dates"?

**Comment by ME-MarvinE** [comment]
I would like to reproduce the issue. How would I "set invalid dates"?

Do I do it by setting the `DayTemplate` to a DayView with `IsInvalid` set to true?

**Comment by jennablkwll** [comment]
@ME-MarvinE - I wanted to disable selection for the next 2 weeks from today.  So I attempted to mark 2 weeks as invalid.  This works initially, but when I change months and come back, the "invalid" is gone.

On calendar set up from my viewmodel:

   for (int i = 0; i < 14; i++)
    {
                var dt = DateTime.Today.AddDays(i);
                var d = BookingCalendar.Days.FirstOrDefault(x => x.DateTime.Date == dt.Date);
                d.IsInvalid = true;
    }

**Comment by ME-MarvinE** [comment]
The Calendar updates the 'IsSelected', 'IsInvalid', 'IsCurrentMonth', and 'IsToday' values of the days internally, as it needs to make sure these values are correct according to the properties in the Calendar such as `TodayDate`, `SelectedDates`, and `DayRangeMinimumDate` and `DayRangeMaximumDate`.

If you want to overwrite this, you can either: 
* Inherit from the Calendar class and override the 'UpdateDay' method (Call the base implementation, then overwrite the `IsInvalid` property of the passed `CalendarDay`)
 
* Subscribe to the `DaysUpdated` event in the Calendar which occurs after the Calendar calls `UpdateDay` on all the days and set the `IsInvalid` on all your days inside the event handler. Keep in mind by doing it this way, you would potentially be setting the value twice (Once by Calendar, then once by you), meaning the bindings would update twice, decreasing performance.

**Comment by jennablkwll** [comment]
Ok, I will try that.  Thanks!

**Comment by jennablkwll** [comment]
Ok - inheriting Calendar and overriding IsDateTimeInvalid worked for me as expected.  Thanks again!
