### ISSUE TITLE
RightArrowCommand, LeftArrowCommand properties changes are not available in latest nuget 4.5.1 MAUI

### ISSUE THREAD

**Issue by satzmuthu** [ME-MarvinE/XCalendar#155]
**RightArrowCommand, LeftArrowCommand properties changes are not available in latest nuget 4.5.1 MAUI**

**Comment by ME-MarvinE** [comment]
Changes on the master branch will be in limbo until a new version is decided to be released. Maybe I could keep these changes in a separate branch in the future but for now, these changes will stay until I add/change more things and release a new version.

**Comment by ME-MarvinE** [comment]
In the 4.5.1 they are still called `ForwardsArrowCommand`

**Comment by ME-MarvinE** [comment]
These changes have been applied in 4.5.2
