### ISSUE TITLE
Set localize manual

### ISSUE THREAD

**Issue by nhhoangit** [ME-MarvinE/XCalendar#165]
I'd like to set localize for navigation and DayOfWeek manually. It's seem not implement this feature.

**Comment by ME-MarvinE** [comment]
Issue #29 asks the exact same thing. Please view the comments for that issue. In short, the calendar's `DayNameTemplate` and `DayNamesTemplate` properties can be used to manually implement translations. Discussion #121 may also be helpful.

**Comment by nhhoangit** [comment]
Issue #29 can be resolve with custom xml below. Thanks
` <xc:CalendarView.DayNameTemplate>
          <DataTemplate>
            <Label HorizontalTextAlignment="Center" x:DataType="{x:Type System:DayOfWeek}"  Text="{Binding .,Converter={StaticResource XCalendarDayConverter}}"/>
          </DataTemplate>
        </xc:CalendarView.DayNameTemplate>`
