### ISSUE TITLE
Shadow on iOS Navigation Arrows

### ISSUE THREAD

**Issue by jfversluis** [ME-MarvinE/XCalendar#2]
There is a shadow under the navigation buttons on iOS. To make it more in line with Android I think those should be disabled or at least have an option to toggle it for people

![image](https://user-images.githubusercontent.com/939291/151773940-5e93794f-7698-4f29-aea2-44e680357dee.png)

**Comment by jfversluis** [comment]
Yeah I think that has a shadow by default indeed, that seems to make sense

**Comment by ME-MarvinE** [comment]
Great! Thanks for the help.
