### ISSUE TITLE
Day Text Color Option

### ISSUE THREAD

**Issue by captclearleft** [ME-MarvinE/XCalendar#24]
Hello, and Thank You!  for such an Awesome project!!!

I am trying to make the XCalendar Have a **"Dark Theme"** - Black Background, white Text,  

Please forgive me as I am not good at Xamarin, and have spent the last couple days trying to create a 
`<xc:CalendarDayView.Style>`
 That does this,  But I cant get it.  

I know on the App.xaml this property changes all the Labels Text 
`<Color x:Key="ContentTextColor">White</Color>`
 (Note - This does not work for me in my own code)

I am sure this is a simple oversite on my part - I apologize (Noob here).  Can someone point me in the right direction to solve this property.?

And is there a better place to post these questions? (I hate taking the developers time away for this basic programming questions).

Thanks - Love this project -Great Job!

(Would like White Text Here on Images below.)

![capture1](https://user-images.githubusercontent.com/44250740/153928821-26d640ec-3052-4c90-aef0-9ce0c47ef96c.PNG)

![capture2](https://user-images.githubusercontent.com/44250740/153928831-bf5454de-2117-4769-92ce-e1e31637b668.PNG)

**Comment by ME-MarvinE** [comment]
No one can really give any useful advice/info without you sharing your code :P. 
  
Knowing where to look for info is always the biggest challenge for new developers I think. I don't know if there is any other place you would ask these questions but I am happy to help.  
  
Do you have intellisense in your XAML? Its very useful for looking for properties you may not know of. If you start typing 'Day' intellisense will find all the properties that have 'day' in their name. Try searching for something like 'Text' or 'Color' or 'TextColor' if you want to find all the properties to do with text and colours.  
  
The wiki for XCalendar is very useful for questions like these and can be found [here](https://github.com/ME-MarvinE/XCalendar/wiki). The section on appearance (where you'll find how to change the text color) can be found [here](https://github.com/ME-MarvinE/XCalendar/wiki/Appearance#monthview).  
  
Please visit the wiki so you know where to look for info, but to answer your question you can set `DayTodayTextColor` and `DayCurrentMonthTextColor` to White. Other text color properties include `DayOutOfRangeTextColor`, `DayOtherMonthTextColor`, and `DaySelectedTextColor`.

**Comment by captclearleft** [comment]
Thank you so much for sharing your time and knowlege - So greatly appreciated!!!!
Love this project, so cool!

  I should proof read everything i write 🤦. My appalogies.  Agreed - post the code is a best practice.  

I am still playing with the Example Project provided.  I have no code changes to show.   

In my images - The background of the Calendar is Black, which hides the "Day Numbers"  simply changing the Xaml CanendarBackGroundColor="Black"

I played with all the properties in Xaml, and the code behind (w intellisense). 

 I cant find the property for all the regular days color.  

As you can see in the images, nearly everything is black (cant deliniate the day numbers).  There are properties for all the important days, but I cant find the property for a regular old unselected day .  I must be a moran, and just not see it.  Haha 🤦

Thank you again

**Comment by ME-MarvinE** [comment]
Don't be so hard on yourself!

The text colour property for a regular day is `DayCurrentMonthTextColor`. Did setting that to white not work?
