### ISSUE TITLE
Setting culture of days of the week

### ISSUE THREAD

**Issue by ivanteles** [ME-MarvinE/XCalendar#29]
How to set the culture to pt-br so that the days of the week are in Portuguese?

**Comment by ME-MarvinE** [comment]
The `CalendarView` has no built-in support for cultures. However it does expose a `DayNameTemplate` property which you can use to implement the Portugese text yourself.

**Comment by ivanteles** [comment]
What kind of data should I pass?
list<string> Days?

**Comment by ivanteles** [comment]
So I made a convert, but the control doesn't pass in my convert!
 
```
<xCalendar:CalendarView.DayNameTemplate>
                    <DataTemplate>
                            <Label Text="{Binding ., Mode=TwoWay, Converter={StaticResource DayConverter}}" />
                    </DataTemplate>
                </xCalendar:CalendarView.DayNameTemplate>
```

**Comment by ME-MarvinE** [comment]
I don't see anything wrong immediately except that the BindingMode does not need to be TwoWay.
You can test whether the value is getting passed or not by setting a Label's text value to `"{Binding .}"` and seeing if it shows anything. If so, then it's something with the converter.

Have you tested that the converter actually works by using it on something simple like a ViewModel property?

A reproduction link would be helpful, or at least the code for the converter.

**Comment by ME-MarvinE** [comment]
I always thought this was optional, but it seems that if `x:DataType` is not set on the `DataTemplate`, the converter won't be called at all.

Here's the example you used with the fix applied:

Using `xmlns:System="clr-namespace:System;assembly=System.Runtime"`
```xaml
<xCalendar:CalendarView.DayNameTemplate>
    <DataTemplate x:DataType="{x:Type System:DayOfWeek}">
        <Label Text="{Binding ., Converter={StaticResource DayConverter}}"/>
    </DataTemplate>
</xc:CalendarView.DayNameTemplate>
```

`{x:Type System:DayOfWeek}` can also be written as `System:DayOfWeek`.

**Comment by ivanteles** [comment]
It was just that! Thank you!

**Comment by nandodefaria** [comment]
> How to set the culture to pt-br so that the days of the week are in Portuguese?

Hi! Can you send me the files, to see how to implement it? Thanks

**Comment by ME-MarvinE** [comment]
I believe you change the value of either `System.Globalization.CultureInfo.CurrentCulture` or `System.Globalization.CultureInfo.CurrentUICulture` to the Portuguese culture. I don't remember if you need to do this before instantiating your calendar.

```C#
System.Globalization.CultureInfo.CurrentCulture = new CultureInfo("pt-br");
```
