### ISSUE TITLE
Assigning templates to selected individual days

### ISSUE THREAD

**Issue by LukasBrits** [ME-MarvinE/XCalendar#33]
Hi,

I've been playing around with XCalendar and it's been fun so far.

My consideration is to use it for an event manager. Everything that I need has been sorted out, but there's one thing that I'm struggling with. Is there a way to change individual days' templates based on certain conditions e.g. a list of dates? The reason is that I'd like to display a simple frame on days that have events scheduled. So far I've been able to get the frame to display based on properties within the CalendarDayView (e.g. IsCurrentMonth, IsEnabled etc.) but I seem to need a way to access it from code, which I haven't been able to figure out.

What I am trying right now is using a template selector but I realize this might not be a viable approach.

Please excuse me if this is a simple question as I am relatively new to Xamarin. Great project btw!

```
<ContentPage.Resources>
        <DataTemplate x:Key="eventCalendarDayViewTemplate"
                      x:DataType="{x:Type xcModels:CalendarDay}">
            <xc:CalendarDayView x:Name="dayCalendar"
                                TodayTextColor="Orange"
                                TodayBorderColor="Transparent"
                                TodayBackgroundColor="Transparent"
                                CornerRadius="10"
                                CalendarView="{Binding ., Source={x:Reference MyCalendar}}"
                                DateTime="{Binding DateTime}"
                                SelectedBackgroundColor="Transparent"
                                SelectedTextColor="Black"
                                ControlTemplate="{StaticResource CalendarViewControlTemplate}">
            </xc:CalendarDayView>
        </DataTemplate>
        <DataTemplate x:Key="genericCalendarDayViewTemplate"
                      x:DataType="{x:Type xcModels:CalendarDay}">
            <xc:CalendarDayView x:Name="dayCalendar"
                                TodayTextColor="Orange"
                                TodayBorderColor="Transparent"
                                TodayBackgroundColor="Transparent"
                                CornerRadius="10"
                                CalendarView="{Binding ., Source={x:Reference MyCalendar}}"
                                DateTime="{Binding DateTime}"
                                SelectedBackgroundColor="Transparent"
                                SelectedTextColor="Black">
            </xc:CalendarDayView>
        </DataTemplate>
        <ControlTemplate x:Key="CalendarViewControlTemplate">
            <Grid>
                <ContentPresenter Margin="0,0,0,5" />
                <Frame x:Name="SelectedEventIndicator"
                       IsVisible="{TemplateBinding IsEnabled}"
                       Margin="0"
                       Padding="0"
                       CornerRadius="100"
                       HasShadow="False"
                       HeightRequest="6"
                       HorizontalOptions="Center"
                       VerticalOptions="End"
                       WidthRequest="20"
                       BackgroundColor="#4ABC5F">
                </Frame>
            </Grid>
        </ControlTemplate>
        <selector:CalendarDayTemplateSelector x:Key="calendarDayTemplateSelector"
                                              EventCalendarDayViewTemplate="{StaticResource eventCalendarDayViewTemplate}"
                                              GenericCalendarDayViewTemplate="{StaticResource genericCalendarDayViewTemplate}" />
    </ContentPage.Resources>
    <StackLayout>
        <Frame Margin="25"
               Padding="0"
               CornerRadius="10"
               HasShadow="False"
               BorderColor="Transparent"
               BackgroundColor="Transparent">
            <StackLayout>
                <xc:CalendarView x:Name="MyCalendar"
                                 BackgroundColor="WhiteSmoke"
                                 NavigationBackgroundColor="#4ABC5F"
                                 SelectionType="Single"
                                 SelectionAction="Replace"
                                 DateSelectionChanged="CalendarView_DateSelectionChanged"
                                 DayTemplate="{StaticResource calendarDayTemplateSelector}">
                </xc:CalendarView>
            </StackLayout>
        </Frame>
        <StackLayout>
            <Frame Margin="25"
                   Padding="0"
                   CornerRadius="10"
                   HasShadow="False"
                   BorderColor="Transparent"
                   BackgroundColor="Transparent">
                <Label x:Name="lblDateSelected"
                       FontSize="30"
                       TextColor="DarkGray"
                       Text="Test text"
                       HorizontalOptions="Center" />
            </Frame>
        </StackLayout>
    </StackLayout>
```

**Comment by ME-MarvinE** [comment]
If you haven't visited it yet, go to the [CalendarDayView](https://github.com/ME-MarvinE/XCalendar/wiki/CalendarDayView) page on the wiki. There it mentions the use of 'Triggers' and a link to Microsoft's documentation.

Triggers are what you can use to change properties (including templates) based on certain conditons.

**Comment by LukasBrits** [comment]
Appreciate the response! Yes I have checked out the page and implemented the Calendar with triggers, but once again I could only customize the day views based on properties within the xaml (e.g. CalendarDayView IsSelected). Is there, for instance, a way to allow a trigger to receive a list of DateTime variables and then apply a control template only to those dates?

**Comment by ME-MarvinE** [comment]
In just trying to understand the issue more:

Say for example you have a list of `Event`  and `Event` just has a single property `DateTime` of type `DateTime`. In the `CalendarDayView`, you want to check if the CalendarDayView's `DateTime` property is the same as one in the list of `Event`.

This is a limitation of Xamsrin Forms that I also want a nice way to do in XAML but a workaround would be to use [ValueConverters](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters) and use the `List.Contains` method.

**Comment by LukasBrits** [comment]
You understood the issue perfectly.
I realize now that this was actually more a Xamarin Forms related question that an XCalendar related one (I blame my inexperience XD). Now at least I know that I wasn't just missing some existing functionality. I can see how your suggested solution should work and will look into it.

Once again thanks for the response and the effort.
Greatly appreciated (hero in my books)!

**Comment by ME-MarvinE** [comment]
No problem, I'll keep this issue open until I make an example of this in the sample app.

**Comment by ME-MarvinE** [comment]
`CommandParameter` may not be bindable but you can use bindable properties in a converter inheriting from `BindableObject`.

**Comment by LukasBrits** [comment]
Great! Thanks again for the assist.
