### ISSUE TITLE
SelectionAction as None

### ISSUE THREAD

**Issue by Cizzl** [ME-MarvinE/XCalendar#35]
Hi,
is there something like SelectionAction as None?
I would like a Calendar which has no ability to add/remove/modify/replace the entries. More likly just have a couple of SelectedDates and when you select one a action executes.  
What I have tried:
When I set SelectionType as None I obviously cannot select any date. 

I just want to select Date only from my SelectedDates (ItemSource).

**Comment by ME-MarvinE** [comment]
So you want to have some dates pre-selected and then not let the user be able to do anything with them except tap them to perform an action?

**Comment by ME-MarvinE** [comment]
Setting SelectionType to None is like a proxy for the 'CurrentMonthCommand' property of the CalendarDayView in the DayTemplate. It just sets that to null.

In your case you need to set the DayTemplate to a CalendarDayView, and set its 'SelectedCommand' to whatever action you want to happen.

**Comment by ME-MarvinE** [comment]
Setting SelectionType to None is like a proxy for the 'CurrentMonthCommand' property of the `CalendarDayView` in the default `DayTemplate`. It just sets that to null.

In your case you need to set the DayTemplate to a `CalendarDayView`, and set its `SelectedCommand` to whatever action you want to happen.
