### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by ddavid-son** [ME-MarvinE/XCalendar#37]
Are you planning to migrate this project to MAUI?

**Comment by ME-MarvinE** [comment]
Now that .NET MAUI is stable and has a release candidate with all the controls needed, yes, I'll be migrating it soon.

**Comment by ME-MarvinE** [comment]
Unfortunately, albeit somewhat expectedly, .NET MAUI RC1 has some bugs that need to be fixed before further development is done.

**Comment by ME-MarvinE** [comment]
Still some issues to work out but there is now a [pre-release for .NET MAUI](https://www.nuget.org/packages/XCalendar.Maui/3.0.0-pre1).
