### ISSUE TITLE
Add a SelectCommand property

### ISSUE THREAD

**Issue by bricefriha** [ME-MarvinE/XCalendar#39]
Hi, first thanks a lot for your work on this plugin, it works very well!
I just would like to submit a feature for it to go even further.

### Description 📜
Currently, there is no way to trigger a Command when we select a date and recently I needed to use one.

**Comment by ME-MarvinE** [comment]
Check out [CalendarDayView](https://github.com/ME-MarvinE/XCalendar/wiki/CalendarDayView) on the wiki.

You can set a Command and CommandParameter for each state. `CurrentMonthCommand` is executed when the user taps on a day that is in the CurrentMonth state, `SelectedCommand` is executed when the user taps on a day that is in the SelectedState etc.

**Comment by ME-MarvinE** [comment]
@bricefriha Did this fix your issue?

**Comment by bricefriha** [comment]
> @bricefriha Did this fix your issue?

Totally sorry I misinterpreted the doc. thanks a lot!
Keep up the hard work! 😉
