### ISSUE TITLE
iOS Sample App Custom Day Names Order Doesn't Seem to Work

### ISSUE THREAD

**Issue by jfversluis** [ME-MarvinE/XCalendar#4]
I'm trying to set the Custom Day Names Order in the sample app on iOS, but it doesn't seem to select the option on the left side and therefore I am not able to add anything else than Mondays. Which in turn causes some weird behavior in the calendar if I actually do add 4 Mondays 😄

![image](https://user-images.githubusercontent.com/939291/151774495-b874fd39-49c0-4f26-a7f3-1da155219947.png)

**Comment by ME-MarvinE** [comment]
Does the VisualState change (Does the background turn grey) at least or does it not respond at all?

**Comment by jfversluis** [comment]
I see kind of the press animation, but doesn't select at all

https://user-images.githubusercontent.com/939291/153063894-574de184-25af-42e0-b3c1-31dce4491e9a.mov

**Comment by ME-MarvinE** [comment]
This may be fixed in 2.1

I suspect the issue was caused by a view inside the `CollectionView` which had `TouchEffect.NativeAnimation="True"`. The new UI now only makes use of commands instead of relying on `CollectionView` selection so any interference should have been resolved.

**Comment by ME-MarvinE** [comment]
Hi @jfversluis, can you check if this is fixed in the latest version of XCalendar.Forms?

**Comment by jfversluis** [comment]
Yep this one seems to work now!
