### ISSUE TITLE
Day Background Color

### ISSUE THREAD

**Issue by captclearleft** [ME-MarvinE/XCalendar#8]
Love this project!!! Fantastic - Thank You!!!

I can't find the code or method to change the **background color** of the **selected day** or (**range of dates**).  

I see in the example the Red oval like rectangle (awesome) - Is there a method so that I can use a different color or shape for selected background.  Or where is that code, and I can help add to the functionality.  Thanks .... 

Update: png added: Referencing - Change color of circled red background colors.  
![xCalendarGitHub1](https://user-images.githubusercontent.com/44250740/151900306-d7579f8f-9fa1-4dad-a410-97811a8e58cf.PNG)

**Comment by captclearleft** [comment]
Is the background color of the Selected Day being controlled by this TouchEffect handler?

<Setter Property="xct:TouchEffect.NormalBackgroundColor" Value="{StaticResource PrimaryColor}" />

If so, How can I easily change the Dates background color dynamically from the code behind.  Similar to the way we can access the Text color - I would like to have different background colors on different days.  
Not sure if this should be a pull request.  Thanks  Again - Awesome !!!

**Comment by ME-MarvinE** [comment]
Yes the TouchEffect handler is controlling the background colour. There is no way to set the background colour without using a template.

I didn't want people to be put off from using templates because if they want to use one they would also have to implement text colour, background colour, corner radius, and anything else that could be set from the Calendar.

Below is the way to make a template and use existing functionality for a CalendarDay. You can see how all the text colour properties make it look more complicated than it is. I don't use code behind, is it hard to do this from there?

```xaml
                                        <DataTemplate x:DataType="{x:Type Models:CalendarDay}">
                                            <xc:CalendarDayView
                                                CalendarView="{Binding ., Source={x:Reference FancyCalendarView}}"
                                                CurrentMonthTextColor="{Binding DayCurrentMonthTextColor, Source={x:Reference FancyCalendarView}}"
                                                DateTime="{Binding DateTime}"
                                                HeightRequest="{Binding DayHeightRequest, Source={x:Reference FancyCalendarView}}"
                                                OtherMonthTextColor="{Binding DayOtherMonthTextColor, Source={x:Reference FancyCalendarView}}"
                                                OutOfRangeTextColor="{Binding DayOutOfRangeTextColor, Source={x:Reference FancyCalendarView}}"
                                                SelectedTextColor="{Binding DaySelectedTextColor, Source={x:Reference FancyCalendarView}}"
                                                TodayTextColor="{Binding DayTodayTextColor, Source={x:Reference FancyCalendarView}}">

                                                <xc:CalendarDayView.ControlTemplate>
                                                    <ControlTemplate>
                                                        <Frame BackgroundColor="Red">
                                                            <ContentPresenter/>
                                                        </Frame>
                                                    </ControlTemplate>
                                                </xc:CalendarDayView.ControlTemplate>

                                            </xc:CalendarDayView>
                                        </DataTemplate>
```

Although I guess it would be better to just have all the simple properties upfront and just have better documentation for using templates - something you can copy paste. More cosmetic properties on the way :)

**Comment by captclearleft** [comment]
(( Again - Thanks so much - This project is Awesome!  ))
I see...  I am not very good at XAML yet, and am not too familiar with ControlTemplates (yet).  

I would like to be able to change the background color of each "Day" "Cell" individually  by querying a database and populating the background colors based on what is going on on that day.  (ie days with nothing going on would be default background white, where days with something going on would be a color based on the event(s) that day...)

Is it possible to make these Control Templates accessible from the Code behind.?  Maybe I could create several with different colors.  
(lol... Im a noob to XAML...  haha

**Comment by captclearleft** [comment]
You are Awesome!  Thanks so much!  

I will share my code when I get this working !!!
